### PR TITLE
[DUOS-2025][risk=no] Remove IT / SO director fields from applicant information section

### PR DESCRIPTION
**Pull request by connorlbark**
### Addresses

https://broadworkbench.atlassian.net/browse/DUOS-2025

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by quazi-h — APPROVED** [review]
Changes look good so far, running locally, the SO and IT Director have a single field each that has the name and email for the individuals. One nit I have is that it might be clearer to have those fields labeled as "Signing Official" and "IT Director" without the "Email" in the header since the value of those fields contains both name and (if available) email, but otherwise looks good and we don't have any duplicate data showing up under the Applicant Information slab.

**Comment by JVThomas** [comment]
> Changes look good so far, running locally, the SO and IT Director have a single field each that has the name and email for the individuals. One nit I have is that it might be clearer to have those fields labeled as "Signing Official" and "IT Director" without the "Email" in the header since the value of those fields contains both name and (if available) email, but otherwise looks good and we don't have any duplicate data showing up under the Applicant Information slab.

Agreed. It was included as a note in the ticket itself

```
Note: Remove the email columns for SO and IT Director. These values are essentially the same value, just displayed in two places. 
```

**Comment by connorlbark** [comment]
ohhh good catch! just updated the labels @quazi-broad @JVThomas

**Review by JVThomas — APPROVED** [review]
Code looks good to me (tested locally)

**Pull request merged**
