### PR TITLE
[DCJ-538] Add All of Us data library

### PR DESCRIPTION
**Pull request by fboulnois**
### Addresses

https://broadworkbench.atlassian.net/browse/DCJ-538

### Summary

Adds the All of Us data library

Screenshot 2024-07-24 at 16-29-49 Broad Data Use Oversight System

### CODE REVIEW

**Review by aarohinadkarni — APPROVED** [review]
nice 👍

**Review by okotsopoulos — APPROVED** [review]
Looks good!

I remember our most recent library addition carried with it a bug on tab switch (I can't recall the specifics off the top of my head).  Is that a risk here?

**Comment by fboulnois** [comment]
> Looks good!
> 
> I remember our most recent library addition carried with it a bug on tab switch (I can't recall the specifics off the top of my head). Is that a risk here?

It wasn't so much the addition of the library itself, rather it uncovered an existing issue with state change when going from one data library to another. This was fixed in this earlier PR: https://github.com/DataBiosphere/duos-ui/pull/2627

**Review by rushtong — APPROVED** [review]
Looks good 👍

**Pull request merged**
