### PR TITLE
DUOS-1781[risk=no] Updated styling for placeholder components on the dar collection review header

### PR DESCRIPTION
**Pull request by quazi-h**
Ticket: [DUOS-1781](https://broadworkbench.atlassian.net/browse/DUOS-1781)

- Updated styling on placeholder components for the dar collection ReviewHeader and DataUseVoteSummary.
- Updated the number of vote result placeholders to 2 since that is the minimum that will be shown.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by shaemarks — COMMENTED** [review]
Placeholder component sizes are a lot closer to the actual page components 👍 
It might be worth updating `TabControl` as well since the placeholder is a lot shorter than the actual tab

**Comment by quazi-h** [comment]
Updated styling in TabControl so the placeholder looks similar to the "Application Information" tab.
When testing the changes with different collections I noticed that it's still somewhat abrupt when viewing a collection with no DataUseVote buckets. I attempted to write some logic in DataUseVoteSummary - where the loadingTemplate is called: but was unable to get it working - I think because the dataUseBuckets/chunkedBuckets variable is not available when isLoading is True.
line 96 in DataUseVoteSummary:
`(dataUseBuckets.length > 0) ? loadingTemplate : null;`

**Review by shaemarks — APPROVED** [review]
Looks good to me! Thanks for the changes!

**Review by JVThomas — APPROVED** [review]
Changes look good to me as well

**Pull request merged**
