### PR TITLE
[DUOS-1876][risk=no] updated table css for mobile view on vote summary card

### PR DESCRIPTION
**Pull request by lu-c**
BEFORE
Screen Shot 2022-06-22 at 1 07 03 PM
Screen Shot 2022-06-22 at 1 07 11 PM

AFTER
Screen Shot 2022-06-22 at 1 04 12 PM
Screen Shot 2022-06-22 at 1 04 24 PM

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rushtong — APPROVED** [review]
LGTM 👍🏽

**Review by shaemarks — COMMENTED** [review]
Changes look good! Should we do anything to the sizing of the pie chart under the Structured Research Purpose slab? Since there's no algorithm decision for the rp vote, we only show the pie chart, which previously filled up the whole space because of the flex box. Now that the pie chart width is set to 50%, the right half of that section is just blank space

Before:
pie chart before


After:
pie chart after

**Comment by lu-c** [comment]
> Changes look good! Should we do anything to the sizing of the pie chart under the Structured Research Purpose slab? Since there's no algorithm decision for the rp vote, we only show the pie chart, which previously filled up the whole space because of the flex box. Now that the pie chart width is set to 50%, the right half of that section is just blank space
> 
> Before: pie chart before
> 
> After: pie chart after

Updated to fix this issue - it'll now check if the second column is going to be rendered, and provides the width part as a style override (imitating how it was handled in the right box)

**Review by shaemarks — APPROVED** [review]
Looks good, thanks for the changes!

**Pull request merged**
