### PR TITLE
[DUOS-2260][risk=no] Fix missing key console errors

### PR DESCRIPTION
**Pull request by rushtong**
This PR adds keys to all of the navigation tabs

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by kaitlynoflaherty — COMMENTED** [review]
I tested this locally and ran into an issue. When I log out and log back in, I can navigate the tabs without any errors. When I reload the page, the same warning pops up. I'm not sure what could be causing it to only appear after reloading the page.
image

**Review by fboulnois — APPROVED** [review]
curious about Kaite's error, otherwise lgtm

**Comment by rushtong** [comment]
> I tested this locally and ran into an issue. When I log out and log back in, I can navigate the tabs without any errors. When I reload the page, the same warning pops up. I'm not sure what could be causing it to only appear after reloading the page.

Thanks @kaitlynoflaherty ... gonna dig in some more, not sure I saw that but could have missed something

**Review by kaitlynoflaherty — APPROVED** [review]
Does the same error occur on your local environment? I think its good otherwise

**Comment by rushtong** [comment]
> Does the same error occur on your local environment? I think its good otherwise

It does. I'm going to close this and we can address it separately.

**Pull request closed without merging**
