### PR TITLE
[DUOS-801] Replace Homepage diagram with updated text version

### PR DESCRIPTION
**Pull request by solideoglori**
\<your comments for this PR go here \>

Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] PR is labeled with a Jira ticket number and includes a link to the ticket
- [ ] PR is labeled with a security risk modifier [no, low, medium, high] 
- [ ] PR describes scope of changes

In all cases:

- [ ] Get a minimum of one thumbs worth of review, preferably 2 if enough team members are available
- [ ] Get PO sign-off for all non-trivial UI or workflow changes
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by solideoglori** [comment]
Dear Reviewer, please feel free to propose changes to center the image.
Note, the image file is intentionally still PNG, not SVG. We are awaiting an updated SVG.

**Review by rushtong — CHANGES_REQUESTED** [review]
If we aren't using the old one, we should delete it. Otherwise, looks good.

**Comment by solideoglori** [comment]
@rushtong updated PR with SVG only and PNG deleted.

**Comment by rushtong** [comment]
@solideoglori - I don't see the deletion of the old image in the changes list. Make sure you don't have any uncommitted changes and push your latest version to github

**Comment by solideoglori** [comment]
Deleted old version of PNG

**Review by rushtong — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
