### PR TITLE
[DUOS-1501][risk=no] Add robust redirects after login

### PR DESCRIPTION
**Pull request by connorlbark**
### Addresses

https://broadworkbench.atlassian.net/browse/DUOS-1501

Example cases which must redirect properly:
- `https://local.broadinstitute.org:3000/dataset_catalog` should redirect to dataset catalog after logging in with an existing user.
- `https://local.broadinstitute.org:3000/home?redirectTo=dataset_catalog` should redirect to dataset catalog after logging in with an existing user.
- `https://local.broadinstitute.org:3000/dataset_catalog` should redirect to dataset catalog after accepting ToS with a new user.
- `https://local.broadinstitute.org:3000/home?redirectTo=dataset_catalog` should redirect to dataset catalog  after accepting ToS with a new user.

Can use https://consent.dsde-dev.broadinstitute.org/#/User/delete_api_user__email_ to delete a user for testing new user flow.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rushtong** [comment]
I notice that the default console pages aren't being navigated to - it stays on the home page after a normal login:

Screen Shot 2022-11-04 at 11 44 52 AM

**Comment by connorlbark** [comment]
> I notice that the default console pages aren't being navigated to - it stays on the home page after a normal login:

👍 should be fixed now!

**Review by rushtong — APPROVED** [review]
👍🏽 Looks great!

**Review by JVThomas — APPROVED** [review]
Tested locally, redirects are working well while enforcing user access rights.

**Pull request merged**
