### PR TITLE
[DUOS-2068][risk=no] Move file type to consent group

### PR DESCRIPTION
**Pull request by connorlbark**
### Addresses

https://broadworkbench.atlassian.net/browse/DUOS-2068

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rushtong** [comment]
I'm a little confused on the implementation here. As I understand it, "Filetype" is an object with three properties, File Type, Functional Equivalence, and # of Participants. Looking at this UI, I still see the "Add New Filetype" button which, I believe, should be in the consent group box as well.

Screen Shot 2022-10-13 at 2 06 52 PM

**Comment by connorlbark** [comment]
@rushtong required a decent amount of refactoring, but just got the full file type section moved to the consent group!

**Review by quazi-h — APPROVED** [review]
I think fields are in the correct place now - I see the three form fields "File Type*", "Functional Equivalence*", and "# of Participants*" at the bottom of the form that appears with "Add Consent Group". Prior to this change, it was possible to select an existing consent group and also provide the file types but with these changes, adding a file type is only possible when adding a new consent group. Is this intentional?

**Review by rushtong — APPROVED** [review]
Changes look good 👍🏽

**Pull request merged**
