### PR TITLE
DUOS-716 Embed PowerBI dashboard in About page

### PR DESCRIPTION
**Pull request by lindojong**
## Addresses
https://broadinstitute.atlassian.net/browse/DUOS-716

Screenshot:
Screen Shot 2020-08-07 at 9 46 33 AM

### CODE REVIEW

**Comment by lindojong** [comment]
Updated screenshot of full width + header:
Screen Shot 2020-08-10 at 12 52 24 PM

**Comment by solideoglori** [comment]
Looks great!

**Review by solideoglori — APPROVED** [review]

**Review by rushtong — APPROVED** [review]
Looks fantastic, thank you! 👍
 
Optional, and for bonus points, there is some invalid nesting on this page, i.e. p->p, p->div, p->h3, etc. I think it would be nice if we could refactor the `p` tags to be `div`s and that should resolve all of the following:
```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
    in p (created by HomeAbout)
    in p (created by HomeAbout)
    in div (created by HomeAbout)
    in div (created by HomeAbout)
    in div (created by HomeAbout)
    in div (created by HomeAbout)
    in HomeAbout (created by Context.Consumer)
    in Route (at Routes.js:51)
    in Switch (at Routes.js:46)
    in Routes (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App (at src/index.js:18)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:17)
Warning: validateDOMNesting(...): <h3> cannot appear as a descendant of <p>.
    in h3 (created by HomeAbout)
    in div (created by HomeAbout)
    in p (created by HomeAbout)
    in div (created by HomeAbout)
    in div (created by HomeAbout)
    in div (created by HomeAbout)
    in div (created by HomeAbout)
    in HomeAbout (created by Context.Consumer)
    in Route (at Routes.js:51)
    in Switch (at Routes.js:46)
    in Routes (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App (at src/index.js:18)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:17)
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by HomeAbout)
    in div (created by HomeAbout)
    in p (created by HomeAbout)
    in div (created by HomeAbout)
    in div (created by HomeAbout)
    in div (created by HomeAbout)
    in div (created by HomeAbout)
    in HomeAbout (created by Context.Consumer)
    in Route (at Routes.js:51)
    in Switch (at Routes.js:46)
    in Routes (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App (at src/index.js:18)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:17)
```
and still retain the same styling.

**Review by rushtong — APPROVED** [review]
Thank you for the changes! 👍

**Pull request merged**
