### PR TITLE
DUOS-1218[risk=no] Updated DAC Chair Font and Button

### PR DESCRIPTION
**Pull request by JVThomas**
Addresses [DUOS-1218](https://broadworkbench.atlassian.net/browse/DUOS-1218)

PR updates font on DAC Chair console to Arial and updated disabled button coloring for disabled. Secondary color was not implemented because only one button appears on the page at a time (Vote and Open never appear together). Refactored style methods to account for disabled button updates on text and icon button.

Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [x] PR is labeled with a Jira ticket number and includes a link to the ticket
- [x] PR is labeled with a security risk modifier [no, low, medium, high] 
- [x] PR describes scope of changes

In all cases:

- [x] Get a minimum of one thumbs worth of review, preferably 2 if enough team members are available
- [x] Get PO sign-off for all non-trivial UI or workflow changes
- [x] Verify all tests go green
- [x] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by raejohanek — CHANGES_REQUESTED** [review]
the new chair console page looks great, I see you made the subheader text larger there, but on the admin manage access and member console the subheader text still looks pretty small. Also, idk what your thoughts were on the table header text, right now its the same as the table body text which looks okay, but maybe we want it bolder than the table body ?

**Review by rushtong — APPROVED** [review]
Changes looks very good, thank you for this!

**Review by raejohanek — CHANGES_REQUESTED** [review]
changes look good! the only places where the subheader text still looks small to me are on the access review page and review results page, both which are in rendered by the access review header

**Review by rushtong — APPROVED** [review]
Reviewed the changes on affected pages - they look great, align well, and improve consistency 👍🏽

**Review by raejohanek — APPROVED** [review]
font and button changes look great!

**Pull request merged**
