### PR TITLE
[DUOS-1332][risk=no] Update LC display

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1332

Note to reviewer, suggest hiding whitespace changes.

## Changes
* With the update to the library card model, the display for users that had LCs threw an error. This PR fixes that error.
* Minor update to `ReviewResults` `useEffect` to remove a console warning about unused dependencies.

As a complication of this, we now have slightly different functionality. We only display the LC for the institution the user is a member of. If there are multiple LCs with different institutions for a single user, we will ignore them. Logically, this makes sense since we now associate users to a signing official based on their institution, and LCs are issued by signing officials, so in practice, a user will not have more than one. If they do, they are not relevant as they are associated to an institution the user is not a member of.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by raejohanek — COMMENTED** [review]
this PR fixes the errors that we saw on dev 👍 I think maybe it could use a style update for the library card / institution name display since it looks a little odd with a long institution name, what do you think?
Screen Shot 2021-07-07 at 11 35 33 AM

**Comment by rushtong** [comment]
> it looks a little odd with a long institution name, what do you think?

I agree, the name is a bit long. Let me see if I can make it wrap lines. The update I did do was to center the image/text and pad it a little more so the background green wasn't too jarring.

**Comment by rushtong** [comment]
@raejohanek: Latest fix: 
Screen Shot 2021-07-07 at 11 43 08 AM

**Review by raejohanek — APPROVED** [review]
update fixes bug and looks good!

**Pull request merged**
