### PR TITLE
[DT-776] Filter by Data Type

### PR DESCRIPTION
**Pull request by fboulnois**
### Addresses

https://broadworkbench.atlassian.net/browse/DT-776

### Summary

Adds a filter for the Data Type (note that in dev we have a bunch of weird selections)

https://github.com/user-attachments/assets/2f160c31-000a-4de3-a907-58b6cfb0676d

----

Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by s-rubenstein — COMMENTED** [review]
How many data types do we expect? I know the long list is on dev, are we expecting much fewer on prod? If it is going to be long, I'd love to think about limiting the amount shown, and figuring out a `see more` story.

**Comment by fboulnois** [comment]
> How many data types do we expect? I know the long list is on dev, are we expecting much fewer on prod? If it is going to be long, I'd love to think about limiting the amount shown, and figuring out a `see more` story.

We have 8 by default, but a user can add their own if they really want (although not all 8 may be shown since it's dynamically populated from the datasets). I agree that long term if the list gets long we should add a separate story to "see more".

**Comment by s-rubenstein** [comment]
Great. I'll flag that as a potential future ticket for Victoria

**Review by s-rubenstein — APPROVED** [review]
LGTM

**Review by rjohanek — APPROVED** [review]
this looks good to me, although is there any kind of testing we want to do here?

**Comment by fboulnois** [comment]
> this looks good to me, although is there any kind of testing we want to do here?

Good idea, let me work on increasing our unit test coverage.

**Pull request merged**
