### PR TITLE
[DUOS-1552][risk=no] multi dataset voting member tab

### PR DESCRIPTION
**Pull request by shaemarks**
[Link to Jira ticket](https://broadworkbench.atlassian.net/browse/DUOS-1552)
Summary of changes:

- Created tab that displays SRP and dataset voting slabs for buckets that the current user can submit votes for as a DAC member
- Added tab to DarCollectionReview page
- Added tests 

Test by navigating to a `http://localhost:3000/dar_collection/{collection id}` page that your DAC is supposed to vote on. Currently slabs for datasets are only displayed if the current user has votes for that bucket.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rushtong** [comment]
Unrelated to code changes in this PR, I'm seeing an error loading the researcher information for DAR Collection id 362 (dar code DAR-437). `ApplicationInformation.js` is failing at line 150 with 
```
Uncaught Error: Objects are not valid as a React child (found: object with keys {approverStatus, email, eraCommonsId, name, title, uuid}). If you meant to render a collection of children, use an array instead.
```

**Review by rushtong — APPROVED** [review]
The member tab looks great! Vote and rationale work as expected. The error case I found looks unrelated to this PR, so 👍🏽

**Comment by rushtong** [comment]
FYI, seeing this in the console:
```
Warning: React does not recognize the `dataCy` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `datacy` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at ResearchProposalVoteSlab
    at div
    at MultiDatasetVotingTab
    at div
    at div
    at DarCollectionReview
```
We may need to adjust what we're doing for testing

**Comment by rushtong** [comment]
Still looking into this ~but I don't think the member votes for the RP election are being passed down to the member tab~. I created an election for DAR-11 and I can see a vote button for the Data Access election(s), but not the RP election(s)

Edit: It does look like the votes are present in the component, but not rendered 

Screen Shot 2022-04-19 at 8 07 21 AM

**Comment by shaemarks** [comment]
> Still looking into this ~but I don't think the member votes for the RP election are being passed down to the member tab~. I created an election for DAR-11 and I can see a vote button for the Data Access election(s), but not the RP election(s)
> 
> Edit: It does look like the votes are present in the component, but not rendered
> 
>
I just merged in the newer PRs (DUOS-1695 added the vote-related subcomponents to the ResearchProposalVoteSlab) so the vote buttons should be appearing now. Sorry about that.

For the error messages with `dataCy`, would changing it to `datacy` fix the problem or would that introduce a different issue?

**Comment by rushtong** [comment]
> I just merged in the newer PRs (DUOS-1695 added the vote-related subcomponents to the ResearchProposalVoteSlab) so the vote buttons should be appearing now. Sorry about that.

Looks great, thank you!

> For the error messages with dataCy, would changing it to datacy fix the problem or would that introduce a different issue?

I just did a search/replace and ran all the component tests - they all pass so I think the lower case version does not break anything.

**Review by rushtong — APPROVED** [review]
Changes look good, thank you 👍🏽

**Review by quazi-h — APPROVED** [review]
Code changes look good to me. I was able to access the Member Vote tab for a dar_collection. The SRP and relevant vote buckets look great.

**Pull request merged**
