### PR TITLE
[DUOS-2974] Refactor to jsx from react-hyperscript-helpers

### PR DESCRIPTION
**Pull request by PintoGideon**
### Addresses

https://broadworkbench.atlassian.net/browse/DUOS-2974

### Summary

Switches from react-hyperscript-helpers to JSX

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by fboulnois — APPROVED** [review]
Tested and looks good 👍 

One minor nit for the future is perhaps for these `hyperscript-helpers` to JSX tickets avoid reformatting the content too much since it makes the diffs more challenging to review.

To be clear, I think it's worth reformatting the style in the future.

**Comment by PintoGideon** [comment]
@fboulnois  Point noted. Thanks :)

**Review by aarohinadkarni — APPROVED** [review]
👍

**Review by rushtong — APPROVED** [review]
Looks and works great, thank you 👍🏽

**Pull request merged**
