### PR TITLE
[DUOS-1777][risk=no] add bypass for lc requirement on dar submission

### PR DESCRIPTION
**Pull request by shaemarks**
[Link to Jira ticket](https://broadworkbench.atlassian.net/browse/DUOS-1777)
Summary of Changes:
- Add field in DAR form data to track if checkbox for NIH dataset use only is checked
- Change hasLibraryCards to libraryCardReqSatisified and modify to include status of check box 
- Add tests

[Link to Consent PR](https://github.com/DataBiosphere/consent/pull/1559)
PR above needs to be used as the backend in order to save the status of the checkbox

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rushtong** [comment]
Something in the validation is triggering Step 1 being invalid, even with the `I am exclusively applying for NIH/NHGRI data (ex. GTex)` checked, which is preventing an otherwise complete DAR from being able to be submitted. Digging!

**Comment by rushtong** [comment]
The `checkNihDataOnly` value doesn't seem to be sent to the back end when clicking `Save`. This also means it isn't being re-populated when the DAR is refreshed, so the user has to re-check that selection.

**Comment by shaemarks** [comment]
> The `checkNihDataOnly` value doesn't seem to be sent to the back end when clicking `Save`. This also means it isn't being re-populated when the DAR is refreshed, so the user has to re-check that selection.

Is this bug occurring even with the [https://github.com/DataBiosphere/consent/pull/1559](https://github.com/DataBiosphere/consent/pull/1559) used as the backend?

**Comment by rushtong** [comment]
>> The checkNihDataOnly value doesn't seem to be sent to the back end when clicking Save. This also means it isn't being re-populated when the DAR is refreshed, so the user has to re-check that selection.

> Is this bug occurring even with the https://github.com/DataBiosphere/consent/pull/1559 used as the backend?

Aha, no, I thought 1559 was merged already - will re-test with that branch.

**Comment by rushtong** [comment]
With the right back end in place, I am able to save the form correctly. Still seeing this for submission though:
> Something in the validation is triggering Step 1 being invalid, even with the `I am exclusively applying for NIH/NHGRI data (ex. GTex)` checked, which is preventing an otherwise complete DAR from being able to be submitted. Digging!

**Review by rushtong — APPROVED** [review]
Looks good, thanks for the changes!

**Review by JVThomas — APPROVED** [review]
Tested locally in conjunction with Consent, the checkbox allows researchers to proceed with the DAR application without an LC.

**Pull request merged**
