### PR TITLE
[DUOS-1943] redirect to edit user page after saving user edits

### PR DESCRIPTION
**Pull request by lu-c**
https://broadworkbench.atlassian.net/browse/DUOS-1943

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by shaemarks — COMMENTED** [review]
Looks good to me! I would suggest adding a try catch and using Notifications.showError if something goes wrong since currently it looks like you'll be redirected without knowing that the change failed to go through

**Review by connorlbark — APPROVED** [review]
looks good pending the try/catch shae mentioned!

**Comment by lu-c** [comment]
> Looks good to me! I would suggest adding a try catch and using Notifications.showError if something goes wrong since currently it looks like you'll be redirected without knowing that the change failed to go through

Updated the code so if it fails, you don't redirect at all

**Review by shaemarks — APPROVED** [review]
Looks good to me! Thanks for the changes!

**Pull request merged**
