### PR TITLE
[DUOS-2125][risk=no] Add Collapsible DAC Member Vote

### PR DESCRIPTION
**Pull request by connorlbark**
### Addresses

https://broadworkbench.atlassian.net/browse/DUOS-2125

The quick mocks show putting this section in a card, but I think the way I implemented is a bit cleaner in context of the rest of the page. Uses the same vote table as before, but updates language to make it clear that it's the dac member votes and not the chair votes. Adds the vote table to the dac member's vote page. I also added this to the member research purpose vote tab, which wasn't in the spec but seemed to be a logical need.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by quazi-h — APPROVED** [review]
These changes are working well for me locally. Checked a few different DAR review pages and observed the collapsible DAC Member Votes component in the Chair and Member slabs, including the RUS slabs. The only nit I have is that the styles do not match up with the mocks on the ticket but I expect that is outside of the scope of this ticket.

**Review by JVThomas — CHANGES_REQUESTED** [review]
Code looks good, but there needs to be an adjustment visually to make the dropdown icon stick out a little more. Making the sub-header and icon bigger should be a quick fix for that

Here's how it currently looks like...
Screen Shot 2022-10-18 at 8 32 04 AM

And here's how scaling up the size can help make the icon more visible...
Screen Shot 2022-10-18 at 8 23 14 AM

**Comment by connorlbark** [comment]
@JVThomas scaled the icon, should be better now! (turns out svg scaling is kind of complicated and doesn't always work as expected... but luckily all i needed was `!important`)

**Review by JVThomas — APPROVED** [review]
LGTM

**Pull request merged**
