### PR TITLE
[DUOS-2774] Update Library Styling

### PR DESCRIPTION
**Pull request by hams7504**
### Addresses
https://broadworkbench.atlassian.net/browse/DUOS-2774

### Summary

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rushtong — APPROVED** [review]
I think this looks good so far and takes us in the right direction. There are some other tweaks that need to be made but can be done in separate tickets.

---
Note the thicker border that stops just past the inner table (upper circle). I think it has to do with the border definitions around the inner table. We should try and get rid of the doubled line and also extend the top of the NEXT row all the way across the screen (see lower circle).
Screenshot 2023-11-27 at 9 28 41 AM

---
The mocks call for some space between the rows. This can also be a separate ticket but should be addressed:

Screenshot 2023-11-27 at 9 29 53 AM

**Comment by hams7504** [comment]
> I think this looks good so far and takes us in the right direction. There are some other tweaks that need to be made but can be done in separate tickets.
> 
> Note the thicker border that stops just past the inner table (upper circle). I think it has to do with the border definitions around the inner table. We should try and get rid of the doubled line and also extend the top of the NEXT row all the way across the screen (see lower circle). Screenshot 2023-11-27 at 9 28 41 AM
> 
> The mocks call for some space between the rows. This can also be a separate ticket but should be addressed:
> 
> Screenshot 2023-11-27 at 9 29 53 AM

Sounds good! I can make a separate ticket for those changes. I didn't end up implementing the space between rows since the ticket did not mention that, but I can make include that in the new ticket as well! Thank you.

**Review by rjohanek — APPROVED** [review]
Approve with some comments/changes - Mainly, the subtable now has headers that wrap to the second line causing a thick header. I think it looked better when the titles could fit all on one line. Maybe you can make the subtable wider? Additionally, minor thing, the mock has a thinner header for both the larger table and the sub table, if you're trying to match the mock I think this should be thinner. Finally, like Greg said, if the thick line could be extended for the entire table instead of stopping around participants I think it would look neater.

**Comment by hams7504** [comment]
> Approve with some comments/changes - Mainly, the subtable now has headers that wrap to the second line causing a thick header. I think it looked better when the titles could fit all on one line. Maybe you can make the subtable wider? Additionally, minor thing, the mock has a thinner header for both the larger table and the sub table, if you're trying to match the mock I think this should be thinner. Finally, like Greg said, if the thick line could be extended for the entire table instead of stopping around participants I think it would look neater.

Thank you! I'll add these suggestions to the new styling ticket

**Comment by hams7504** [comment]
Created new ticket to address additional styling updates: https://broadworkbench.atlassian.net/browse/DUOS-2820

**Pull request merged**
