### PR TITLE
[DUOS-743][risk=no] DUOS Signing Official Info page

### PR DESCRIPTION
**Pull request by lindojong**
Addresses: https://broadinstitute.atlassian.net/browse/DUOS-743

Screen Shot 2020-09-10 at 11 58 32 AM

Creates the new Signing Official Info page, and links to it from the home page.

Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [x] PR is labeled with a Jira ticket number and includes a link to the ticket
- [x] PR is labeled with a security risk modifier [no, low, medium, high] 
- [x] PR describes scope of changes

In all cases:

- [ ] Get a minimum of one thumbs worth of review, preferably 2 if enough team members are available
- [x] Get PO sign-off for all non-trivial UI or workflow changes
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by solideoglori** [comment]
Hi Linda, one minor question - can we resize the people icons such that they are all the same size? If this, requires a change from UX folks, let's move forward without it.

**Review by solideoglori — APPROVED** [review]

**Comment by lindojong** [comment]
@solideoglori Do you mean the people icons within the images, or resize so that the whole images are the same height? If it's the second option, I can adjust it!

**Comment by JVThomas** [comment]
Can you adjust the sizing of the images and the text? The text is kind of small and the images are massive which makes the page look off.

Screen Shot 2020-09-11 at 9 48 58 AM

The above is just a quick example (play around with the sizing), but the idea is that proper sizing between text, heading, and images can help "balance" a page.

**Comment by solideoglori** [comment]
Resizing the whole image would be ideal, thanks for clarifying!

**Pull request merged**
