### PR TITLE
[DCJ-210][DCJ-194][DCJ-204] Refactor react-hyperscript-helper components to JSX

### PR DESCRIPTION
**Pull request by PintoGideon**
### Addresses

https://broadworkbench.atlassian.net/browse/DCJ-210
https://broadworkbench.atlassian.net/browse/DCJ-194
https://broadworkbench.atlassian.net/browse/DCJ-204

### Summary

1. Remove the use of react-hyperscript-helpers
2. Update the file extensions from js to jsx

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rushtong** [comment]
@PintoGideon - Can we generate separate Jira tickets for this PR as well as for https://github.com/DataBiosphere/duos-ui/pull/2554? Bundling both of them under the same epic is confusing for tracking purposes - thank you!

**Comment by PintoGideon** [comment]
@rushtong, Thank you. I have updated the links to point to their individual Jira tickets.

**Review by rushtong — APPROVED** [review]
Manually tested these for regressions, all looks good 👍🏽

**Review by fboulnois — APPROVED** [review]
looks good, thank you 👍

**Pull request merged**
