### PR TITLE
[DCJ-179] Completely remove `react-hyperscript-helpers`

### PR DESCRIPTION
**Pull request by fboulnois**
### Addresses

https://broadworkbench.atlassian.net/browse/DCJ-179

### Summary

Now that https://github.com/DataBiosphere/duos-ui/pull/2582 has gone in, we can completely remove `react-hyperscript-helpers`.

#### Background

This is the final piece of a conversion process that began in November of 2023.

The DUOS (now Data Custodian Journeys, or DCJ) team has been participating in the Terra UI working group meetings and aligning the DUOS UI codebase with Terra UI best practices where feasible. One of the decision taken by the working group was to migrate away from `react-hyperscript-helpers` to using regular JSX. 

The pros and cons of `react-hyperscript-helpers` have been vigorously debated in the Terra UI working group meetings, but in short the main cons were that the library has not been updated since 2018 and it is a relatively niche library, whereas React examples assume use of JSX or TSX.

For the DCJ team, this is especially important since we are a smaller team and have a lot of co-ops with React and JSX experience but not `react-hyperscript-helpers` experience, so this increases onramp time. The removal of outdated libraries from our UI is also important to lower our complexity, dependency churn, and our security upkeep burden.

#### Acknowledgements 

A huge thanks to all the teammates who participated in migrating over these components to JSX, especially @PintoGideon who converted some of our largest and most challenging components.

#### Statistics

By the numbers, this represents:

- 125 components migrated over to JSX
- 22516 total lines converted
- 33 PRs to migrate various components
- 1.02 components migrated per working day

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rushtong — APPROVED** [review]
Looks good after a rebase 👍🏽  🍾

**Review by PintoGideon — APPROVED** [review]
Thanks for the changes. LGTM !!

**Review by aarohinadkarni — APPROVED** [review]
looks good, thank you!! 🎉 🙌

**Review by okotsopoulos — APPROVED** [review]

**Review by okotsopoulos — APPROVED** [review]
Thrilling!

**Pull request merged**
