### PR TITLE
[DCJ-200] Refactor FAQs.js to JSX

### PR DESCRIPTION
**Pull request by PintoGideon**
### Addresses

https://broadworkbench.atlassian.net/browse/DCJ-200

### Summary

1. Remove the use of react-hyperscript-helpers
2. Remove unused code
3. Update the file ext from js to jsx
4. Delete the file as it is not referenced by any routes or components.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rushtong — APPROVED** [review]
👍🏽  Side note, there are no links or routes to this page - I'm thinking this is a very outdated page as there is an external FAQs page here: https://broad-duos.zendesk.com/hc/en-us/articles/360059957092-Frequently-Asked-Questions-FAQs-

**Comment by fboulnois** [comment]
> 👍🏽 Side note, there are no links or routes to this page - I'm thinking this is a very outdated page as there is an external FAQs page here: https://broad-duos.zendesk.com/hc/en-us/articles/360059957092-Frequently-Asked-Questions-FAQs-

Should we simply remove this page? We can always restore it from git history if necessary.

**Comment by rushtong** [comment]
> > 👍🏽 Side note, there are no links or routes to this page - I'm thinking this is a very outdated page as there is an external FAQs page here: https://broad-duos.zendesk.com/hc/en-us/articles/360059957092-Frequently-Asked-Questions-FAQs-
> 
> Should we simply remove this page? We can always restore it from git history if necessary.

@PintoGideon That's a better idea, please do remove it 👍🏽

**Comment by PintoGideon** [comment]
Will do @fboulnois  @rushtong  Thank you both !!

**Review by rushtong — APPROVED** [review]
Thanks for the update 👍🏽

**Review by fboulnois — APPROVED** [review]
👍

**Pull request merged**
