### PR TITLE
[DUOS-1740][risk=no] Version updates for all actions

### PR DESCRIPTION
**Pull request by rushtong**
### Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1740

### Summary
Update for all actions
Remove unused combine prs action
Adds [dependabot check](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) for actions

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by fboulnois — APPROVED** [review]
Since we're bumping major versions have we checked that these have complete compatibility with our current actions?

**Comment by rushtong** [comment]
> Since we're bumping major versions have we checked that these have complete compatibility with our current actions?

The successful action runs are essentially that compatibility check

**Comment by rushtong** [comment]
This is the test that's failing - it's flaky, will file a new ticket for it:
```
  │ ✖  MultiDatasetVoteTab/multi_dataset_v      00:05       19       18        1        -        - │
  │    ote_slab.spec.js                                                                            │
```

**Review by aarohinadkarni — APPROVED** [review]
looks good 👍

**Pull request merged**
