### PR TITLE
[DUOS-2126][risk=no] Layout and other adjustments for UX.

### PR DESCRIPTION
**Pull request by otchet-broad**
[DUOS-2126](https://broadworkbench.atlassian.net/browse/DUOS-2126) is largely a layout adjustment based on a mock from UX.

In addition to the layout adjustment, the following changes were implemented:
1) SimpleTable will correctly sort values if null values are encountered (sortVisibleTable->utils.js)
2) The DarTable will now properly include a row key for child elements when a row is expanded
3) The algorithm result answer (YES/NO) has been stylized to display the value Yes in DUOS Green, No in DUOS Red, and anything else in black.
4) Some files were migrated from hyperscript helpers to JSX.
5) When DataUsePills are built, they now include a unique key.
6) Where necessary tests were updated to use the JSX Cypress "data-cy" tag.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

[DUOS-2126]: https://broadworkbench.atlassian.net/browse/DUOS-2126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DUOS-2126]: https://broadworkbench.atlassian.net/browse/DUOS-2126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rushtong — DISMISSED** [review]
Tested styles locally, changes look reasonable to me. I haven't seen the mocks with the blue bordered voting panels, but am likely behind the times on recent changes. 👍🏽

**Comment by connorlbark** [comment]
image
this looks great, but I think the Yes and No buttons should go underneath `(Vote and Rationale cannot be updated after submitting)`. Or, at the very least, given some space. It doesn't have the right flow to my eyes to be on the right side of that text, and so close to it. however, the changes made visually look much much better than before.

**Review by quazi-h — COMMENTED** [review]
The vote information for members and chairs have been moved correctly to the right side of the card but I agree with Connor's suggestions - the "YES" "NO" vote choices should go under the question instead of at the end of the line. Currently the alignment of the vote choice buttons looks a little awkward. All other changes outside of the layout adjustment look good to me.

**Comment by rushtong** [comment]
@quazi-broad, @connorlbark - I've updated the layout a bit so the chair console Yes/No buttons render below the warning text. I had to make a couple other style changes to get the vote graph box to show up in a relatively legible format. I'm not fully satisfied with the extra white space around that graph, but I think that might be beyond the scope of what this PR was intended to accomplish.

**Review by quazi-h — APPROVED** [review]
Thank you for the changes, the buttons are now rendering under the warning text on the chair console which looks a lot better.

**Pull request merged**
