### PR TITLE
[DUOS-1083][risk=no] Update Logo

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1083

Update favicons and logo images/alignment

### Compressed, with Messages, Not Signed in
Screen Shot 2021-03-17 at 1 35 16 PM

### Expanded, with Messages, Not Signed in
Screen Shot 2021-03-17 at 1 35 53 PM

### Expanded, with Messages, Signed in
Screen Shot 2021-03-17 at 1 36 04 PM

### Expanded, No Messages, Signed in
Screen Shot 2021-03-17 at 1 37 53 PM

### Compressed, No Messages, Signed in
Screen Shot 2021-03-17 at 1 38 33 PM

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] PR is labeled with a Jira ticket number and includes a link to the ticket
- [ ] PR is labeled with a security risk modifier [no, low, medium, high] 
- [ ] PR describes scope of changes

In all cases:

- [ ] Get a minimum of one thumbs worth of review, preferably 2 if enough team members are available
- [ ] Get PO sign-off for all non-trivial UI or workflow changes
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rushtong** [comment]
Reviewer note, the failed actions are showing up incorrectly - each of them has a subsequent successful run.

**Review by raejohanek — APPROVED** [review]
Changes look good!

**Comment by rushtong** [comment]
@raejohanek - if you want to re-review, please do - I forgot to push my latest changes up and just realized that. All changes are now reflected in github.

**Review by raejohanek — APPROVED** [review]

**Comment by rushtong** [comment]
Have a 👍🏽  from Jonathan in slack.

**Pull request merged**
