### PR TITLE
[DUOS-2163][risk=no] Add NIH Insitutional Certification Upload to Data Submission Consent Group

### PR DESCRIPTION
**Pull request by connorlbark**
### Addresses

I'm not exactly sure how file uploads will work for the Data Submission Form. As it is, this will expose a file object for each consent group, which can be used in any way once we're ready to send the form data.

https://broadworkbench.atlassian.net/browse/DUOS-2163

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rushtong** [comment]
> I'm not exactly sure how file uploads will work for the Data Submission Form.

You can look at the existing stub API to see this in action. It will take any number of files and validate their name and size per our standard file processing logic. That's all it does right now ... we need to expand the stub API to do the actual work of saving the files appropriately.

**Comment by connorlbark** [comment]
> You can look at the existing stub API to see this in action. It will take any number of files and validate their name and size per our standard file processing logic. That's all it does right now ... we need to expand the stub API to do the actual work of saving the files appropriately.

Ahh yes, I see this now. The only thing here is that the current data submission form does not have a submit button. I am not sure if that is within the scope of this ticket to add.

**Review by quazi-h — APPROVED** [review]
New file upload for new Consent Groups under the Data Access Governance on the new data_submission_form looks good and is working well when testing locally. I couldn't find a related mock on Invision to reference but the styling looks good to me.

**Comment by rushtong** [comment]
> > You can look at the existing stub API to see this in action. It will take any number of files and validate their name and size per our standard file processing logic. That's all it does right now ... we need to expand the stub API to do the actual work of saving the files appropriately.
> 
> Ahh yes, I see this now. The only thing here is that the current data submission form does not have a submit button. I am not sure if that is within the scope of this ticket to add.

I think you're right, enabling the form is not in scope here.

**Review by rushtong — APPROVED** [review]
👍🏽 Looks good in testing. I have concerns about this approach that need to be hashed out separately so they should not hold up this PR.

**Pull request merged**
