### PR TITLE
DDO-2531 Automatically deploy duos to dev after PR merge [low]

### PR DESCRIPTION
**Pull request by choover-broad**
This PR is a small CI/CD change that shamelessly copies @jack-r-warren's build reporting workflow to DUOS, so that new DUOS builds are automatically deployed to dev on PR merge.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by otchet-broad — COMMENTED** [review]
Quick questions: 

- Other projects related to DUOS ([consent](https://github.com/DataBiosphere/consent/blob/develop/.github/workflows/build.yaml) and [ontology](https://github.com/DataBiosphere/consent-ontology/blob/develop/.github/workflows/build.yaml)) doing something very similar.  Would it be better to consider updating the existing action (or creating a new one) on the terra-helmfile project to perform these steps? 
- Should I create PRs for these or will you be taking care of this?
- Is there a notification process I missed for where these changes are discussed so I can be more proactive in the future?

**Comment by choover-broad** [comment]
hey @otchet-broad, let me clarify: since forever, deploys to Terra's dev environment have *only* been triggered on commits to firecloud-develop's dev branch. If it seemed like duos was being automatically deployed to dev before, what was likely happening is that at roughly the same time or shortly afterwards, someone else merged a commit to firecloud-develop which re-deploys all services in dev.

This PR is an improvement on that behavior, to always trigger duos to be deployed to dev when a PR is merged, regardless of whether someone has touched firecloud-develop recently.

Consent and ontology should also be updated to use these new workflows, and it would be fantastic if you could make those PRs when you have a chance. I will note that PR merges to those repos also cause commits to firecloud-develop's dev branch, so making those changes aren't as urgent (they are already being auto-deployed).

**Review by otchet-broad — APPROVED** [review]
Thanks @choover-broad!

**Review by rushtong — APPROVED** [review]
Thanks for this! 👍🏽

**Pull request merged**
