### PR TITLE
[DUOS-1879][risk=no] Updated vote summary box flex box

### PR DESCRIPTION
**Pull request by lu-c**
- Updated the styles

Really thin
Screen Shot 2022-06-14 at 5 05 58 PM

Kinda thin
Screen Shot 2022-06-14 at 5 06 10 PM

Normal width
Screen Shot 2022-06-14 at 5 06 17 PM

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by rushtong — APPROVED** [review]
Nice work! 👍🏽

**Comment by JVThomas** [comment]
@rushtong @lu-c The boxes aren't fixed width anymore, they adapt to the size of the bucket name.

Screen Shot 2022-06-16 at 7 47 18 AM

If we wan't to go down this route that's fine, but what happens if there's 40+ boxes and a good chunk of them are DS buckets with different diseases?

**Comment by rushtong** [comment]
> If we wan't to go down this route that's fine, but what happens if there's 40+ boxes and a good chunk of them are DS buckets with different diseases?

Great point. We should probably cap the width at some point. I think in slack, we discussed `DS-` + 5 characters, then adding `...`

**Review by JVThomas — DISMISSED** [review]
See comments made above regarding the issue with adaptable sizes.

**Comment by lu-c** [comment]
Screen Shot 2022-06-16 at 7 30 46 PM

Added cap to the votebox width at 170px - does this address the issue for you?

**Comment by rushtong** [comment]
The cap works for me!

**Review by JVThomas — APPROVED** [review]
`maxWidth` on the boxes looks good to me

**Pull request merged**
