### PR TITLE
DCJ-387: Promote DAA functionality to staging

### PR DESCRIPTION
**Pull request by rushtong**
### Addresses
https://broadworkbench.atlassian.net/browse/DCJ-387

### Summary
* Update all DAA related functionality so it is available on staging
* Centralizes the logic in a utility that can serve as a foundation for common DAA logic.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by aarohinadkarni — COMMENTED** [review]
Looks good! Two quick things: 

I think we need to pull develop into this branch— there's one more PR that got merged that is using the `(checkEnv(envGroups.DEV)` that we can replace with the `DAAUtils.isEnabled()` call.

Also, I believe with this promotion, we will also have to upload DAAs, most importantly a Broad DAA to staging consent— there currently are no DAAs uploaded to staging so some of the pages on staging are breaking (DAA Associations, DAR form, etc.). Essentially the work of https://broadworkbench.atlassian.net/browse/DCJ-389 but on a much smaller scale for staging.

**Comment by rushtong** [comment]
> Also, I believe with this promotion, we will also have to upload DAAs, most importantly a Broad DAA to staging consent— there currently are no DAAs uploaded to staging so some of the pages on staging are breaking (DAA Associations, DAR form, etc.). Essentially the work of https://broadworkbench.atlassian.net/browse/DCJ-389 but on a much smaller scale for staging.

For staging, we can add a Dac DAA manually and set up DAA relations for everyone.

**Comment by rushtong** [comment]
> I think we need to pull develop into this branch— there's one more PR that got merged that is using the `(checkEnv(envGroups.DEV)` that we can replace with the `DAAUtils.isEnabled()` call.

@aarohinadkarni - This is now complete, thank you!

**Review by okotsopoulos — APPROVED** [review]
Looks good to me 👍

**Review by aarohinadkarni — APPROVED** [review]
thank you! 👍

**Pull request merged**
