### PR TITLE
DUOS-1291[risk=no]Update Admin Console to pull DAR Collections

### PR DESCRIPTION
**Pull request by JVThomas**
Addresses [DUOS-1291](https://broadworkbench.atlassian.net/browse/DUOS-1291)

PR adds a new Admin Console button that redirects the Admin to a Dar Collection Manage Page (new). Page contains a table that will list collections and available actions for that collection alongside a functional search bar and table sorting via column headers.

**NOTE:** The old DAR button/page is still present for now, but it can be removed at a later date once the Collection feature has been tested/used after deployment.

Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by quazi-h — APPROVED** [review]
Changes here look good. I also loaded your branch locally and the new button on the admin console looks good. On the Manage Dar Collections page everything looks good, including the columns and available actions. The only issue I noticed was that I couldn't tell what is being searched when using the Search Bar and wasn't able to filter by Title keywords.

**Review by rushtong — APPROVED** [review]
Looks good! 👍🏽

**Review by quazi-h — APPROVED** [review]
Search is working perfectly for me now!

**Review by rushtong — APPROVED** [review]
👍🏽

**Pull request merged**
