### PR TITLE
[DUOS-1740][risk=no] Upgrade node-forge

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1740

Updates node-forge. Used [this guide](https://itnext.io/fixing-security-vulnerabilities-in-npm-dependencies-in-less-than-3-mins-a53af735261d) as a template for addressing it. This should address the following security alerts:

* https://github.com/DataBiosphere/duos-ui/security/dependabot/34
* https://github.com/DataBiosphere/duos-ui/security/dependabot/35
* https://github.com/DataBiosphere/duos-ui/security/dependabot/36

The only affected functionality is in `google-auth-library` which I manually tested 👍🏽 

Other updates to workflow actions are due to `npm ci` failures.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by JVThomas** [comment]
Couple of questions/comments

1) How is this a vulnerability for us? We only use the library for the cypress e2e tests to mock the backend response. It's never used in the application. `npm audit --production` shows 0 vulnerabilities

2) If you're going to override specific versions, use npm's override feature instead of `npm-force-resolutions`. It's already being used in our current `package.json` file
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by rushtong** [comment]
> How is this a vulnerability for us? We only use the library for the cypress e2e tests to mock the backend response. It's never used in the application. npm audit --production shows 0 vulnerabilities

`node-forge` is a dependency of `google-auth-library` which is production code for us. I can't speak to why `npm audit --production` does what it does. Additionally, we have these three alerts that we need to deal with:

- https://github.com/DataBiosphere/duos-ui/security/dependabot/34
- https://github.com/DataBiosphere/duos-ui/security/dependabot/35
- https://github.com/DataBiosphere/duos-ui/security/dependabot/36

**Comment by rushtong** [comment]
> If you're going to override specific versions, use npm's override feature instead of npm-force-resolutions. It's already being used in our current package.json file

I will give this a shot - didn't know that it would do what we needed.

**Comment by rushtong** [comment]
> > How is this a vulnerability for us? We only use the library for the cypress e2e tests to mock the backend response. It's never used in the application. npm audit --production shows 0 vulnerabilities
> 
> `node-forge` is a dependency of `google-auth-library` which is production code for us. I can't speak to why `npm audit --production` does what it does. Additionally, we have these three alerts that we need to deal with:
> 
> * https://github.com/DataBiosphere/duos-ui/security/dependabot/34
> * https://github.com/DataBiosphere/duos-ui/security/dependabot/35
> * https://github.com/DataBiosphere/duos-ui/security/dependabot/36

Ah - pretty sure I misunderstood that `google-auth-library` is not in prod code. We might be able to ignore this altogether.

**Comment by rushtong** [comment]
This PR is unnecessary, affected library is not in production code.

**Pull request closed without merging**
